Fee.create(fee_name: 'Enrolment Fee', start_date: Date.today , end_date: Date.today + 1.year , amount: 100, fee_type: 'ENROLMENT')
@maths_fee = Fee.create(fee_name: 'Maths Fee', start_date: Date.today , end_date: Date.today + 1.year , amount: 160, fee_type: 'MONTHLY')
@english_fee = Fee.create(fee_name: 'English Fee', start_date: Date.today , end_date: Date.today + 1.year , amount: 160, fee_type: 'MONTHLY')
@maths = Subject.create(subject_name: 'Mathematics', lowest_grade_taught: '1', highest_grade_taught: '7', fee_id: @maths_fee.id)
@english = Subject.create(subject_name: 'English', lowest_grade_taught: '1', highest_grade_taught: '7', fee_id: @english_fee.id)
@maths_fee.update_attributes(subject_id: @maths.id)
@english_fee.update_attributes(subject_id: @english.id)
Pack.create(name: '5++', description: 'A pack for advanced fifth graders', action_required: 'Nothing', subject_id: @maths.id)
Pack.create(name: '5--', description: 'A pack for less competent fifth graders', action_required: 'Nothing', subject_id: @maths.id)
User.create(first_name: 'Employee', surname: 'User', role: 'employee', postal_address: 'some address', city: 'some city', zip_code: 151, state: 'HA', email: 'employee@gmail.com', password: 'tania551')
User.create(first_name: 'Admin', surname: 'User', role: 'admin', postal_address: 'some address', city: 'some city', zip_code: 151, state: 'HA', email: 'admin@gmail.com', password: 'tania551')
Offer.create(offer_name: 'Premier Group X English', offer_description: 'Starting English Offer', start_date: Date.today , end_date: Date.today + 1.year, subject_id: 2)
Offer.create(offer_name: 'Premier Group X Mathematics', offer_description: 'Starting Maths Offer', start_date: Date.today , end_date: Date.today + 1.year, subject_id: 1)